### ISSUE TITLE
XMLParser version not working on Pharo 7 and 8

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-contributions/XML-XPath#2]
Version 3.5.0 of XMLParser does not fully work with Pharo 8, because it uses class SHTextStylerST80 which does not exist. [Commit 0effb91 of XMLParser](https://github.com/pharo-contributions/XML-XMLParser/commit/0effb9130748e417844886b3cb5992644757b206#diff-ccaca85fcda91a52646273fdc271a4fe) fixes the problem, so XPath should use it or XMLParser should have a release 3.5.1.
Because of this problem, following book "Scraping HTML with XPath" leads to an error.

**Comment by astares** [comment]
Using a fresh Pharo 8 - loading XPath (with dependency on XMLParser 3.5.x) is working

![image](https://user-images.githubusercontent.com/5980033/73635762-7dd4e680-4664-11ea-945a-204c56a984d8.png)
