### ISSUE TITLE
license file is missing ... link from README.md is a dead link ...

### ISSUE THREAD

**Issue by dalehenrich** [pharo-contributions/XML-XPath#4]
I just forked the XML-* projects and noticed that this project doesn't have a license file ...

**Comment by astares** [comment]
Looks like we forgot to add it. Code is MIT (following initial project http://smalltalkhub.com/PharoExtras/XPath/)

Added the missing file https://github.com/pharo-contributions/XML-XPath/blob/master/LICENSE
