### ISSUE TITLE
Missing GLMHighlighterTextStylerDecorator in Pharo 9

### ISSUE THREAD

**Issue by bpieber** [pharo-contributions/XML-XPath#6]
Loading XPath in does not work anymore because it depends on GLMHighlighterTextStylerDecorator which was removed in Pharo 9 with this Pull Request:
https://github.com/pharo-project/pharo/pull/9067

The easiest way to fix it would probably be to reintroduce the class in Pharo 9.

**Comment by astares** [comment]
Load the "Core" of XPath without the tools and it should run fine

**Comment by bpieber** [comment]
Thank you for the suggestion @astares! However, I miss the tree view in the inspector if I don't load the tools.

**Comment by astares** [comment]
@bpieber Yes - this needs to be rewritten using Spec2 tooling now (see NewTools for examples). Feel free to help and contribute

**Comment by astares** [comment]
Inspector tree view is provided in Pharo 12/13
